package finalprojectdb;

public class NewDriver {
	
	public static void main(String args[])
	{
		String tupleValues[][] = {{"Name","Apple"},{"Price","100"},{"Year","2010"}};
		/*
		String valuesToFind[][] = {
				{"Name","Apple","String","="},
				{"Price","90","int",">"},
				{"Price","100","int","="},
				{"Price","40","int",">"},
				{"Price","120","int",">"},
				{"Price","60","int","<"},
				{"Price","130","int","="},
				};
				*/
		
		PredicateGenerator p = new PredicateGenerator();
		String valuesToFind[][] = p.generatePredicates(1000000);
		
		//this is used to print the predicates
		/*
		for(int i=0; i<valuesToFind.length;i++)
		{
			for(int j=0; j<valuesToFind[i].length; j++)
			{
				System.out.print(valuesToFind[i][j]+" ");
			}
			System.out.println();
		}
		*/
		
		Tuple t = new Tuple();
		NaiveSigGen nsg = new NaiveSigGen();
		t.addMembersAndValues(tupleValues);
		nsg.initializeQueryFieldsToCheck(valuesToFind);
		
		long startTime = System.nanoTime();
		int sign[] = nsg.generateSig(t);
		long endTime = System.nanoTime();
		System.out.println("Naive Sign Generator took " + (endTime - startTime) + " nanoseconds");
		
		
		System.out.println("Sign values generated by Naive are ");
		for(int i=0; i<sign.length;i++)
		{
			System.out.print(sign[i]+" ");
		}
		System.out.println();
		
		
		
		OptSigGen osg = new OptSigGen();
		
		t.addMembersAndValues(tupleValues);
//		osg.resetMetaDataArrays();
		startTime = System.nanoTime();
		osg.initializeQueryFieldsToCheck(valuesToFind);
		endTime = System.nanoTime();
		System.out.println("initializeQueryFieldsToCheck took " + (endTime - startTime) + " nanoseconds");
		
		startTime = System.nanoTime();
		osg.valueDistiller(valuesToFind);
		endTime = System.nanoTime();
		System.out.println("valueDistiller took " + (endTime - startTime) + " nanoseconds");
//		osg.printMetaDataHolders();
		//osg.randomDriverFunction();
		System.out.println();
		
		startTime = System.nanoTime();
		osg.triggerSignatureSet(t);
		endTime = System.nanoTime();
		System.out.println("Optimized Signature Generator took " + (endTime - startTime) + " nanoseconds");
		
		
		osg.printSignBits();
//		osg.printEqHash();

	}

}
